module.exports = {
  ISSUE_STATUS: {
    SUBMITTED: "SUBMITTED",
    ACKNOWLEDGED: "ACKNOWLEDGED",
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    RESOLVED: "RESOLVED",
    VERIFIED: "VERIFIED"
  },

  ISSUE_CATEGORY: {
    ROAD: "ROAD",
    WATER: "WATER",
    ELECTRICITY: "ELECTRICITY",
    SANITATION: "SANITATION",
    OTHER: "OTHER"
  }
};
